# -*- coding: utf-8 -*-
"""Reprosesing Data CIC IDS 2017

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaoxRVSJIS5Nd1ZNKazDRnxoBwS1ZzD8
"""

import pandas as pd
from google.colab import files

# NAMA FILE PARQUET YANG BERBEDA DI SINI

file_parquet_1 = "DDoS-Friday-no-metadata.parquet"          # khusus DDoS
file_parquet_2 = "Portscan-Friday-no-metadata.parquet"      # khusus PortScan
file_parquet_3 = "Benign-Monday-no-metadata.parquet" # khusus Normal/Benign



# 2. BACA DAN BERSIHKAN KETIGA FILE
df1 = pd.read_parquet(file_parquet_1)
df2 = pd.read_parquet(file_parquet_2)
df3 = pd.read_parquet(file_parquet_3)

# Bersihkan nama kolom dari spasi
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()
df3.columns = df3.columns.str.strip()

# 3. POTONG MASING-MASING HANYA 2.000 BARIS SAJA (Untuk penghematan RAM!)
# Kita ambil sampel secara acak agar datanya representatif
df_node1_mini = df1.sample(n=2000, random_state=42)
df_node2_mini = df2.sample(n=2000, random_state=42)
df_node3_mini = df3.sample(n=2000, random_state=42)

# 4. SIMPAN MENJADI 3 CSV YANG BERBEDA KARAKTER
print("\nMenyimpan ke 3 file CSV spesialis...")
df_node1_mini.to_csv("dataset_node1_ddos.csv", index=False)
df_node2_mini.to_csv("dataset_node2_portscan.csv", index=False)
df_node3_mini.to_csv("dataset_node3_benign.csv", index=False)

# 5. DOWNLOAD KE LAPTOP
print("Mengirim data ke laptopmu...")
files.download("dataset_node1_ddos.csv")
files.download("dataset_node2_portscan.csv")
files.download("dataset_node3_benign.csv")

print("Selesai, Query & Resize Database Node 1, Node 2, Node 3...")